version: "3.9"

services:
  papermc:
    image: "marctv/minecraft-papermc-server:latest"
    container_name: papermc
    restart: always
    ports:
      - "25565:25565"
    env_file:
      - .env
    volumes:
      - "./data:/data"
